name: gym_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.9
  fl_chart: ^1.0.0
  iconsax: ^0.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/google_logo.png
